[versions]
spring-boot = "4.1.1"
springdoc = "3.1.1"
junit5 = "5.14.4"
jqwik = "1.10.1"
pitest = "1.30.0"
pitest-junit5 = "1.2.3"
spotless = "8.10.3"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-kafka = { module = "org.springframework.boot:spring-boot-starter-kafka" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient" }
spring-boot-starter-resource-server = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server" }
spring-boot-starter-authorization-server = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
postgresql = { module = "org.postgresql:postgresql" }
kafka-clients = { module = "org.apache.kafka:kafka-clients" }
springdoc-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version.ref = "springdoc" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka" }
testcontainers-toxiproxy = { module = "org.testcontainers:testcontainers-toxiproxy" }
awaitility = { module = "org.awaitility:awaitility" }
assertj = { module = "org.assertj:assertj-core" }
junit5-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
pitest-cli = { module = "org.pitest:pitest-command-line", version.ref = "pitest" }
pitest-junit5 = { module = "org.pitest:pitest-junit5-plugin", version.ref = "pitest-junit5" }
