package tally.platform.error;

/** The closed list of error codes an API response can carry. */
public enum ErrorCode {
  VALIDATION_FAILED(400),
  MALFORMED_REQUEST(400),
  IDEMPOTENCY_KEY_REQUIRED(400),
  UNAUTHENTICATED(401),
  FORBIDDEN(403),
  NOT_FOUND(404),
  METHOD_NOT_ALLOWED(405),
  REQUEST_IN_FLIGHT(409),
  CLIENT_EXISTS(409),
  REFERENCE_CONFLICT(409),
  PAYLOAD_TOO_LARGE(413),
  UNSUPPORTED_MEDIA_TYPE(415),
  IDEMPOTENCY_KEY_REUSED(422),
  INSUFFICIENT_FUNDS(422),
  ACCOUNT_FROZEN(422),
  ACCOUNT_CLOSED(422),
  ACCOUNT_NOT_EMPTY(422),
  CURRENCY_MISMATCH(422),
  SAME_ACCOUNT(422),
  INTERNAL_ACCOUNT(422),
  AMOUNT_OVERFLOW(422),
  NOT_REVERSIBLE(422),
  ALREADY_REVERSED(422),
  HOLD_NOT_ACTIVE(422),
  HOLD_EXPIRED(422),
  CAPTURE_EXCEEDS_HOLD(422),
  SCHEDULE_NOT_ACTIVE(422),
  CASE_CLOSED(422),
  INTERNAL_ERROR(500),
  STATEMENT_UNAVAILABLE(502),
  RETRY_EXHAUSTED(503),
  SERVICE_UNAVAILABLE(503);

  private final int status;

  ErrorCode(int status) {
    this.status = status;
  }

  public int status() {
    return status;
  }
}
