package tally.ledger.core;

public enum RuleCode {
  INSUFFICIENT_FUNDS,
  ACCOUNT_FROZEN,
  ACCOUNT_CLOSED,
  ACCOUNT_NOT_FOUND,
  CURRENCY_MISMATCH,
  SAME_ACCOUNT,
  INTERNAL_ACCOUNT,
  AMOUNT_OVERFLOW,
  NOT_REVERSIBLE,
  ALREADY_REVERSED,
  HOLD_NOT_ACTIVE,
  HOLD_EXPIRED,
  CAPTURE_EXCEEDS_HOLD,
  UNBALANCED,
  INVALID_AMOUNT,
  INVALID_CURRENCY,
  INVALID_EXPIRY
}
